### PR TITLE
Implement FXAA algorithm

### PR DESCRIPTION
**Pull request by jiangdunchun**
实现fxaa算法

### CODE REVIEW

**Comment by jiangdunchun** [comment]
OK, I have fixed the "VK_DEPENDENCY_BY_REGION_BIT" problem push a new commitment

**Comment by huandzh** [comment]
Are there any performance impacts when adding `VK_IMAGE_USAGE_SAMPLED_BIT` flag to all buffers?

**Comment by jiangdunchun** [comment]
well,  i think FXAA is a meaningful feature for the purpose of game engine study. 
To the performance  impacts  of removing "VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT", i will create a new buffer.

**Comment by YuqiaoZhang** [comment]
> > > Are there any performance impacts when adding `VK_IMAGE_USAGE_SAMPLED_BIT` flag to all buffers?
> > 
> > 
> > I agree with you, "VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT" should NOT be removed. Another backup buffer should be created.
> 
> To the performance impacts of removing "VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT", i will create a new buffer to do the FXAA pass. @YuqiaoZhang , is that OK?

Definitely! This buffer may be used by other post processing effects, for which the input attachment is NOT enough, such as SSAO. Perhaps two buffers (odd and even) should be created.

**Comment by jiangdunchun** [comment]
> > > > Are there any performance impacts when adding `VK_IMAGE_USAGE_SAMPLED_BIT` flag to all buffers?
> > > 
> > > 
> > > I agree with you, "VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT" should NOT be removed. Another backup buffer should be created.
> > 
> > 
> > To the performance impacts of removing "VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT", i will create a new buffer to do the FXAA pass. @YuqiaoZhang , is that OK?
> 
> Definitely! This buffer may be used by other post processing effects, for which the input attachment is NOT enough, such as SSAO. Perhaps two buffers (odd and even) should be created.

I have made a new commitment for creating two buffers for post processing effects, and using one of them for FXAA.

**Pull request merged**
