### PR TITLE
Fix header file include  errors

### PR DESCRIPTION
**Pull request by ReFantasy**
change #include <execution> to #include <exception>

### CODE REVIEW

**Comment by ReFantasy** [comment]
> Please change your development environment.

also be C++17

**Comment by BoomingTech-YuqiaoZhang** [comment]
Anyway, this header is defined by the C++ standard, and thus should not be removed.
Please change your development environment to be suitable to the C++ standard.

**Comment by ReFantasy** [comment]
> Anyway, this header is defined by the C++ standard, and thus should not be removed.
> Please change your development environment to be suitable to the C++ standard.

sorry. I try again. <exception> is no needed, but <execution> is error.

**Comment by ReFantasy** [comment]
sorry. I try again.  exception is no needed, but execution is error.

**Comment by BoomingTech-YuqiaoZhang** [comment]
Perhaps, you can update the system version of your macos.

**Comment by ReFantasy** [comment]
> Perhaps, you can update the system version of your macos.

ok.thanks.

**Pull request closed without merging**
